### ISSUE TITLE
' Included'  annotation should not be mandatory

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#4]
On line 1158 in annotatedTRC2bids:
`single_annotation(annots,'Included',ch);` throws an error if 'Included' annotation is absent. 'Included' is considered compulsory, but isn't specified as such.

**Comment by WillemiekZ** [comment]
I disagree the 'Included' and 'Format' annotation should not be mandatory. 
They should. You need them to make different montages than average reference (f.e. bipolar)...

**Comment by PauluzzS** [comment]
We need them, but according to the specification/pipeline:
> one cECoG should have these annotations: Format, Included, Silicon, SOZ, RA (...)
We could change the specification if it makes more sense to have it in every file.

**Comment by WillemiekZ** [comment]
I think it's safer & not that much work when you're already doing it, to put it in every file. Also of eventually you might add something to a subselection of TRC files, and have to put them also in BIDS?

**Comment by dvanblooijs** [comment]
I think that it's not safer persé when you put Format etc in all files. Since copying is not very easy, it is prone to mistakes between two different ECoGs while they should be the same. I'll check why this is giving errors, because I think that once it is in BIDS, you don't need to make this file for each ECoG. It is the same for all ECoGs in one session.
